spring:
  application:
    name: ssm
  profiles:
    active: local
  datasource:
    name: mysql_ssm
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql8.0以前使用com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #通过这句配置将druid连接池引入到我们的配置中，spring会尽可能判断类型是什么，然后根据情况去匹配驱动类。
    #druid相关配置
    druid:
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 5
      max-active: 100
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接 ms
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

server:
  port: 7799
  servlet:
    context-path: /ssm

mybatis-plus:
  type-aliases-package: com.hong.ssm.domain
  mapper-locations: classpath:mapper/*.xml