spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/zzxypm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root